### ISSUE TITLE
Writable grep buffer and apply the changes to files.

### ISSUE THREAD

**Issue by hongyi-zhao** [jimporter/urgrep#3] opened 2021-10-21 00:50 UTC
Can urgrep support the feature similar to that provided by [Emacs-wgrep](https://github.com/mhayashi1120/Emacs-wgrep):

`Writable grep buffer and apply the changes to files `

Regards,
HZ

**Comment by jimporter** [comment] 2021-10-21 02:30
If you load `urgrep-wgrep.el` in your favorite way (I like `use-package` myself), it should work. I've only used the wgrep integration very lightly, but everything seems to work. If you do find a bug, feel free to file a new issue summarizing the problem(s).

Duplicate of #2.

**Closed as completed by jimporter** 2021-10-21 02:30 UTC

**Comment by hongyi-zhao** [comment] 2021-10-21 02:38
Do you mean something like this?
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep") 
  :config (load "urgrep-wgrep.el" nil t t)
)
```

**Comment by jimporter** [comment] 2021-10-21 03:18
I do this, although there might be better ways to handle it:

```elisp
(use-package urgrep
  :load-path (lambda () (expand-file-name "urgrep/" user-config-dir)))

(use-package urgrep-wgrep
  :load-path (lambda () (expand-file-name "urgrep/" user-config-dir))
  :after (urgrep))
```

Something like this might work for you, although I've never used `straight`, so you might need to tweak this:

```elisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep") 
  :config (use-package urgrep-wgrep))
```

**Comment by hongyi-zhao** [comment] 2021-10-21 03:53
Sorry for this later reply and revision on this issue. I rechecked all of the above methods and none of them worked. See the following for more detailed description.

1.

```emacs-lisp
(use-package urgrep
  :load-path (lambda () (expand-file-name "urgrep/" user-config-dir)))

(use-package urgrep-wgrep
  :load-path (lambda () (expand-file-name "urgrep/" user-config-dir))
  :after (urgrep))
```

The above configuration will trigger the following Warnings:
```
Error (use-package): Failed to parse package urgrep: Symbol’s value as variable is void: user-config-dir Disable showing Disable logging
Error (use-package): Failed to parse package urgrep-wgrep: Symbol’s value as variable is void: user-config-dir Disable showing Disable logging
```

2.
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep")
  :config
  (load "urgrep-wgrep.el" nil t t)
  )
```
and
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep")
  :config
  (require 'urgrep-wgrep)
  )
```
The above two configurations will trigger the following Warnings:

`Error (use-package): urgrep/:config: Cannot open load file: No such file or directory, wgrep Disable showing Disable logging`

3.
```emacs-lisp
(use-package urgrep
  :straight (:host github :repo "jimporter/urgrep") 
  :config (use-package urgrep-wgrep))
```
The above configuration will trigger the following Warnings:
`
Error (use-package): urgrep/:config: Could not find package urgrep-wgrep. Updating recipe repositories: (org-elpa melpa gnu-elpa-mirror el-get emacsmirror-mirror) with ‘straight-pull-recipe-repositories’ may fix this Disable showing Disable logging`

**Comment by hongyi-zhao** [comment] 2021-12-01 05:31
See [here](https://github.com/raxod502/straight.el/issues/892#issuecomment-983303009) for the `straight` based solution with `use-package` integration.
